### ISSUE TITLE
Problems with kerosene (an possibly with other fluids)

### ISSUE THREAD

**Issue by freelancerleno** [gegy1000/PracticalSpaceFireworks#11]
I have a problem when it comes to producing kerosene and therefore to fill the rocket.
There seems to be a conflict with PneumlaticCraft kerosene.
In this screenshot, the bucket of kerosene in JEI does not appear and the texture is not displayed as it should.
![Screenshot_2](https://user-images.githubusercontent.com/38593390/55674871-9ea0a400-58ba-11e9-8521-3a650d8c60e9.png)
Out of curiosity, on the second one, I try to put the PneumaticCraft kerosene but it doesn't work.
![Screenshot_3](https://user-images.githubusercontent.com/38593390/55674910-40c08c00-58bb-11e9-971f-f93ca659efef.png)
At the same time, I'm going to check on the side of Galacticraft which also has liquid oxygen but this time, the liquids are not replaced. The temperatures of the fluids are not the same (300K for Galacticraft against 30K for Practical Space Fireworks). However, the 2 liquids are not compatible with each other.
Apart from the problem with kerosene, is it intended that the fluids are not compatible?

Sorry for my bad english.

Thanks!

**Comment by xyberviri** [comment]
I came here to check if this was compatible with pneumatic craft, might want check their repo out and build in compatibility i wanna stick this in my mod pack cause this would mate perfectly with them. They also have compressed air. 

https://github.com/TeamPneumatic/pnc-repressurized
