### ISSUE TITLE
Kerosene Extractor Only accepts wood.

### ISSUE THREAD

**Issue by DragonSlayer696** [gegy1000/PracticalSpaceFireworks#13]
So I used the kerosene extractor and it would not let me put coal or charcoal into it, I hooked up a hopper to it which forced the coal in but it just ate it and did nothing with it only thing i could get to work was logs. I am using version 0.2.0.7 I'm not sure if it's just me cause I am the only one experiencing this. But since it works with logs its not that big of a issue cause logs are more convenient to access but the wiki says it accepts Coal/Charcoal/Logs.

**Comment by tterrag1098** [comment]
Probably due to missing oredictionary names. Thanks for the report.
